services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./Backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/quizapp
      JWT_SECRET: "any_long_random_string_here_for_dev"
      CLERK_SECRET_KEY: "sk_test_1yfgfzYHhegK54MNsETjClxtxiP8R5Lbyy2XRgrESu"
      ADMIN_SECRET_CODE: "youcef16_demo_secret!"
      PORT: "4000"
      CORS_ORIGIN: "*"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ""
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
